small speed up by skipping files listed in the catalog

diff --git a/bin/renameByHash b/bin/renameByHash
--- a/bin/renameByHash
+++ b/bin/renameByHash
@@ -6,40 +6,45 @@ source $(dirname "$0")/runFunction
 
 # array to hold hash to file name mappings
 declare -A hashes=()
+declare -a names=()
 
-function loadSummaryFile() {
-    if [ ! -f .summary ]; then
-        echo "no .summary file"
+function main() {
+    # validate our arguments or process help
+    case "$1" in
+      '-h' | '--help' | '-?') usage;;
+      '--') shift;;
+    esac
+
+    local dir="${1:-.}"
+    if [ -n "$dir" -a ! -d "$dir" ]; then
+        echo "Error: expecting a directory as an argument -- $dir"
         exit 1
     fi
 
-    local line
-    while read line; do
-        local hash=${line:0:32} name="${line:34}"
-        hashes+=( [$hash]="$name" )
-    done < .summary
-}
 
-function main() {
-    test $# -eq 0 && usage
+    loadMD5Hashes  "$dir/.summary" || {
+        echo "'No catalog files present"
+        exit 1
+    }
 
-    loadSummaryFile
+    local -a unmatchedNames
+    read -a unmatchedNames < <(findUnmatchedFiles < <(generateFileLists "$dir"/.summary "$dir"))
+
 
     local name newName
     local miss=0 hit=0 total=0
-    for name in *; do
+    for name in "${unmatchedNames[@]}"; do
         test ! -f "$name" && continue
 
         ((++total))
-        read hash junk < <(md5sum "$name")
+        read hash junk < <(md5sum $dir/"$name")
 
     newName="${hashes[$hash]}"
         if [ -n "$newName" -a "$name" != "$newName" ]; then
             ((++hit))
             echo "moved $hit files"
-            mv -i "$name" "$newName"
+            : mv -i "$dir/$name" "$dir/$newName"
         else
-            test "$name" = "$newName" && continue
             echo "MISSED: $name"
             ((++miss))
         fi
@@ -47,6 +52,16 @@ function main() {
 
     echo 
     echo "$hit hits, $miss misses out of $total files"
+}
+
+function generateFileLists() {
+    cat <(cut -c35- .summary | uniq) \
+        <(find . -maxdepth 1 -type f -exec basename '{}' \;) \
+        <(echo .summary; echo .summary; echo .vcatalog; echo .vcatalog)
+}
+
+function findUnmatchedFiles() {
+    sort | uniq -u
 }
 
 
